version: '3.9'

services:
  pop-node:
    build: .
    container_name: pop-node
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./start.sh:/start.sh:ro             # start.sh dışarıdan alınacak
      - ./pipe:/root/pipe:ro                # config.json ve pop dışarıdan okunacak
    environment:
      - POP_CONFIG_PATH=/root/pipe/config.json
      - POP_INVITE_CODE=yaz
    entrypoint: ["/bin/bash", "/start.sh"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
