version: '3.9'

services:
  pop-node:
    build: .
    container_name: pop-node
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./pipe/config.json:/root/pipe/config.json:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
